# Generated by Django 4.2.4 on 2023-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=5, verbose_name='Sigla')),
                ('active', models.BooleanField(default=False, verbose_name='¿Activo?')),
                ('floor', models.CharField(max_length=5, verbose_name='Piso')),
                ('office', models.CharField(max_length=10, verbose_name='Oficina N°')),
            ],
        ),
    ]
