# Generated by Django 4.2.5 on 2023-09-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_departamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('name', 'short_name')},
        ),
    ]
