# Generated by Django 4.2.5 on 2023-09-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(max_length=30, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades del empleado',
                'ordering': ['ability'],
            },
        ),
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'Mi empleado', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
        migrations.AddField(
            model_name='empleado',
            name='abilities',
            field=models.ManyToManyField(to='app_empleado.abilities'),
        ),
    ]
