# Generated by Django 4.2.5 on 2023-09-22 20:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empleado', '0005_employee_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='observations',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
