# Generated by Django 4.2.5 on 2023-10-03 13:23

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_departamento', '0002_alter_departamento_unique_together'),
        ('app_empleado', '0006_alter_employee_observations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
                'ordering': ['job'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='abilities',
            field=models.ManyToManyField(to='app_empleado.abilities', verbose_name='Habilidades'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_departamento.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='observations',
            field=ckeditor.fields.RichTextField(blank=True, default='', verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empleado.jobs', verbose_name='Puesto'),
        ),
    ]
